// ---------- story.js : all text, EN + TA ----------
const Story = (() => {
  const T = {
    en: {
      p1: "1279. The Chola line is breaking. The king's last ship leaves at night — carrying his infant heir, his oldest advisor, and the enemy's god.",
      p2: "The golden Fish of the Pandyas. Seized in war a century before. The Pandyas never got their god back. One family never forgot.",
      p3: "“When the tiger wakes, a messenger will come from Tanjore. Follow him home.” — Then silence. Seven hundred years of it.",
      p4: "2026. Kasimedu harbour, Chennai. Kumaran and Selvam — porters, friends since school — sign on with a heritage expedition heading east. The pay is good. Too good.",
      p5: "Meera, an archaeology student, comes too. Her father vanished out there three years ago. She has his notebook. Half of it is a map. The other half is a warning.",
      p6: "Day 9. An island no chart shows. Yazhini, who funds all of this, says: “We go inland at first light.” Meera reads a line from the notebook and goes quiet.",
      y1: "Porters first. Across the wreck. The water only looks deep.",
      m1: "The notebook says the sea here breathes. Watch for it to pull back. Then go.",
      k1: "Selvam. Stay where I can see you.",
      s1: "You stay where I can see you, machan.",
      y2: "Leave him. He signed the same paper you did.",
      porter: "Your water. Press E to give it.",
      porter_done: "You gave him your water. Yazhini saw. Meera saw.",
      t1_done: "Three porters didn't make that. Yazhini didn't look back once.",
      m2: "My father wrote about the things in this forest. He wrote: “they listened to me cry for an hour and never found me.”",
      s2: "So we don't cry. Got it.",
      t2_done: "He was right. They never once looked up. They don't have anything to look with.",
      m3: "This is the last page with a drawing. After this… he wrote in the dark.",
      k3: "Then we go where the drawing ends.",
      t3_done: "Beyond this gorge the notebook stops making sense. Words in old Tamil. A tiger, drawn nine times.",
      restart: "The island took one of you. It doesn't get to keep you. Again.",
      c_wait: "Wait for the wave to pull back. Then go.", c_go: "Now. Go now.", c_surge: "It's coming back — get high!",
      c_listen: "They can't see you. They can hear you.", c_move: "Move. Now. While they're turned.", c_freeze: "Don't move. Don't. Move.",
      c_rope: "Don't let go. Whatever you hear.", c_tie: "Tie it off, Selvam.", c_swing: "Let go at the top of the swing.", c_hold: "Kumaran — hold the rope. Now.",
      r1_title: "TRIAL I — THE DROWNED REEF",
      r1: ["Cross the wreckage together. Both of you must reach the far shore.", "Every few seconds the sea SURGES. Low planks flood. If you are standing on one when it does — you are gone.", "KUMARAN: stand at the base of a tilted plank and HOLD Shift to brace it flat. Selvam can then cross it.", "SELVAM: climb vines with ↑. At the top of the cliff, press E to tie the plank down with a vine — then Kumaran can let go and cross.", "If one of you dies, you both restart. It's short. Breathe."],
      r2_title: "TRIAL II — THE BLIND HUNTERS",
      r2: ["Reach the far edge of the forest without being caught.", "The hunters have no eyes. They HEAR. Walking is quiet. Running far, jumping and landing are loud.", "SELVAM: press E to throw a stone ahead. Every hunter nearby walks to the sound for a few seconds.", "KUMARAN: move while they are distracted. Stand still when a hunter turns to listen — a still body makes no sound.", "Caught = both restart."],
      r3_title: "TRIAL III — THE ROPE GORGE",
      r3: ["Get both of you across the gorge. Two parts. One rope.", "PART 1 — KUMARAN: stand at the anchor post and HOLD Shift. Keep the tension needle inside the gold band. When the rope JERKS (red flash), tap Space to pull it back.", "SELVAM: press E at the edge to grab the rope. While it is taut, hold → to cross hand-over-hand. If tension leaves the band you slip back. If it hits zero, you fall.", "PART 2 — roles swap. SELVAM: press E at the far post and HOLD Shift. KUMARAN grabs the rope and crosses. He is heavier — tension drops faster. Don't let go."],
      act1_end_title: "END OF ACT I",
      act1_end: "The sea. The hunters. The gorge. Three of the seven trials are behind you.\n\nThis is the v1 build. Trials IV–VII, the Kingdom, and what is written on Kumaran's back are coming.",
      hud_k: "KUMARAN", hud_s: "SELVAM",
      ready: "READY — waiting for the other player…",
      brace: "HOLD Shift to brace", vine_drop: "E — tie the plank", stone: "E — throw stone", tension: "TENSION", tie: "E — tie off", grab: "E — grab rope", letgo: "SPACE — let go",
      dead_k: "Kumaran", dead_s: "Selvam",
    },
    ta: {
      p1: "1279. சோழ வம்சம் உடைகிறது. அரசனின் கடைசி கப்பல் இரவில் புறப்படுகிறது — குழந்தை வாரிசு, முதிய அமைச்சர், மற்றும் எதிரியின் கடவுள் அதில்.",
      p2: "பாண்டியர்களின் தங்க மீன். நூறு வருடம் முன் போரில் பறிக்கப்பட்டது. பாண்டியர்களுக்கு அவர்கள் கடவுள் திரும்பவே இல்லை. ஒரு குடும்பம் மட்டும் மறக்கவில்லை.",
      p3: "“புலி விழிக்கும் போது, தஞ்சையிலிருந்து ஒரு தூதுவன் வருவான். அவனைப் பின்தொடர்ந்து வீடு போங்கள்.” — பிறகு மௌனம். எழுநூறு வருட மௌனம்.",
      p4: "2026. காசிமேடு துறைமுகம், சென்னை. குமரன், செல்வம் — சுமைதூக்கிகள், பள்ளி நண்பர்கள் — கிழக்கே செல்லும் ஒரு பாரம்பரிய ஆய்வுப் பயணத்தில் சேர்கிறார்கள். சம்பளம் நல்லா இருக்கு. ரொம்ப நல்லா.",
      p5: "மீரா, தொல்லியல் மாணவி, கூட வருகிறாள். அவள் அப்பா மூணு வருஷம் முன் அங்கே காணாமல் போனார். அவர் நோட்டு அவளிடம். பாதி வரைபடம். மீதி எச்சரிக்கை.",
      p6: "நாள் 9. எந்த வரைபடத்திலும் இல்லாத தீவு. இதற்கெல்லாம் பணம் போடும் யாழினி: “விடியலில் உள்ளே போகிறோம்.” மீரா நோட்டில் ஒரு வரி படித்துவிட்டு அமைதியாகிறாள்.",
      y1: "சுமைக்காரங்க முதல்ல. கப்பல் இடிபாடு வழியா. தண்ணி ஆழம்னு தெரியும், ஆனா இல்ல.",
      m1: "இங்க கடல் மூச்சு விடுதுன்னு நோட்டுல இருக்கு. அது பின்னால இழுக்கிற வரைக்கும் பாருங்க. அப்புறம் போங்க.",
      k1: "செல்வம். நான் பார்க்கிற இடத்துலயே இரு.",
      s1: "நீ நான் பார்க்கிற இடத்துல இரு மச்சான்.",
      y2: "விட்டுட்டு போ. நீ கையெழுத்து போட்ட அதே பேப்பர்ல அவனும் போட்டான்.",
      porter: "உன் தண்ணி. கொடுக்க E அழுத்து.",
      porter_done: "உன் தண்ணியை அவனுக்குக் கொடுத்தே. யாழினி பார்த்தா. மீரா பார்த்தா.",
      t1_done: "மூணு சுமைக்காரங்க இதை தாண்டல. யாழினி ஒரு தடவை கூட திரும்பிப் பார்க்கல.",
      m2: "இந்தக் காட்டுல இருக்கிறவைப் பத்தி அப்பா எழுதியிருக்கார்: “நான் ஒரு மணி நேரம் அழுததை அவை கேட்டுட்டே இருந்தன, என்னைக் கண்டுபிடிக்கவே இல்லை.”",
      s2: "அப்போ நாம அழக்கூடாது. புரிஞ்சது.",
      t2_done: "அவர் சொன்னது சரி. அவை ஒரு தடவை கூட மேல பார்க்கல. பார்க்க அவைக்கு எதுவும் இல்ல.",
      m3: "இதுதான் படம் வரைஞ்ச கடைசி பக்கம். இதுக்கப்புறம்… இருட்டுல எழுதியிருக்கார்.",
      k3: "அப்போ படம் முடியிற இடத்துக்கு போவோம்.",
      t3_done: "இந்தப் பள்ளத்தாக்குக்கு அப்புறம் நோட்டுக்கு அர்த்தமே இல்ல. பழைய தமிழ் வார்த்தைகள். ஒரு புலி, ஒன்பது தடவை வரைஞ்சிருக்கு.",
      restart: "தீவு உங்கள்ல ஒருத்தரை எடுத்துச்சு. வச்சுக்க முடியாது. மறுபடியும்.",
      c_wait: "அலை பின்னால போற வரைக்கும் இருங்க. அப்புறம் போங்க.", c_go: "இப்போ. இப்போவே போங்க.", c_surge: "திரும்ப வருது — மேல ஏறுங்க!",
      c_listen: "அவைக்கு கண் இல்ல. காது இருக்கு.", c_move: "நகருங்க. இப்போ. அவை திரும்பியிருக்கும்போது.", c_freeze: "அசையாதீங்க. அசையவே. கூடாது.",
      c_rope: "விடாதே. என்ன சத்தம் கேட்டாலும்.", c_tie: "கட்டு செல்வம்.", c_swing: "ஊஞ்சல் மேல போகும்போது விடு.", c_hold: "குமரன் — கயிற்றை பிடி. இப்போ.",
      r1_title: "சோதனை I — மூழ்கிய பாறை",
      r1: ["இடிபாடுகளை ஒன்றாகக் கடங்கள். இருவரும் அக்கரை சேர வேண்டும்.", "சில நொடிக்கு ஒரு முறை கடல் பொங்கும். தாழ்வான பலகைகள் மூழ்கும். அப்போ அதில் நின்றால் — போய்விட்டீர்கள்.", "குமரன்: சாய்ந்த பலகையின் அடியில் நின்று Shift அழுத்திப் பிடித்தால் பலகை நேராகும். செல்வம் கடக்கலாம்.", "செல்வம்: ↑ கொண்டு கொடி ஏறு. மேலே E அழுத்தி பலகையை கொடியால் கட்டு — அப்புறம் குமரன் விட்டுட்டு கடக்கலாம்.", "ஒருவர் இறந்தால் இருவரும் மறுபடி. குட்டி சோதனை. மூச்சு விடுங்க."],
      r2_title: "சோதனை II — குருட்டு வேட்டைக்காரர்கள்",
      r2: ["பிடிபடாமல் காட்டின் மறுமுனை சேருங்கள்.", "வேட்டைக்காரர்களுக்கு கண் இல்லை. காது உண்டு. நடப்பது அமைதி. ஓடுவது, குதிப்பது, தரையிறங்குவது சத்தம்.", "செல்வம்: E அழுத்தி முன்னால் கல் எறி. அருகிலுள்ள ஒவ்வொரு வேட்டைக்காரனும் சில நொடி அந்தச் சத்தத்தை நோக்கிப் போவான்.", "குமரன்: அவை திசை திரும்பியிருக்கும்போது நகரு. வேட்டைக்காரன் கேட்கத் திரும்பினால் அசையாமல் நில் — அசையாத உடலுக்கு சத்தம் இல்லை.", "பிடிபட்டால் = இருவரும் மறுபடி."],
      r3_title: "சோதனை III — கயிற்றுப் பள்ளம்",
      r3: ["இருவரும் பள்ளத்தைக் கடக்க வேண்டும். இரண்டு பகுதி. ஒரே கயிறு.", "பகுதி 1 — குமரன்: நங்கூரக் கம்பத்தில் நின்று Shift அழுத்திப் பிடி. இழுவிசை முள்ளை தங்க வளையத்துக்குள் வை. கயிறு இழுக்கும்போது (சிவப்பு) Space தட்டு.", "செல்வம்: விளிம்பில் E அழுத்திக் கயிறு பிடி. இறுக்கமாக இருக்கும்போது → பிடித்து கை மாறி கை கடக்கு. இழுவிசை வளையத்தை விட்டால் பின்னால சறுக்குவே. பூஜ்யம் ஆனால் விழுவே.", "பகுதி 2 — பாத்திரம் மாறும். செல்வம்: மறுமுனை கம்பத்தில் E அழுத்தி Shift பிடி. குமரன் கயிறு பிடித்துக் கடப்பான். அவன் கனம் — இழுவிசை வேகமாகக் குறையும். விடாதே."],
      act1_end_title: "அங்கம் I முடிவு",
      act1_end: "கடல். வேட்டைக்காரர்கள். பள்ளம். ஏழில் மூன்று சோதனைகள் முடிந்தன.\n\nஇது v1 build. சோதனைகள் IV–VII, அரசு, மற்றும் குமரன் முதுகில் எழுதியிருப்பது வரப்போகிறது.",
      hud_k: "குமரன்", hud_s: "செல்வம்",
      ready: "தயார் — மற்றவருக்காகக் காத்திருக்கிறோம்…",
      brace: "Shift பிடி — தாங்கு", vine_drop: "E — பலகையைக் கட்டு", stone: "E — கல் எறி", tension: "இழுவிசை", tie: "E — கட்டு", grab: "E — கயிறு பிடி", letgo: "SPACE — விடு",
      dead_k: "குமரன்", dead_s: "செல்வம்",
    }
  };
  const t = id => (T[E.st.lang] && T[E.st.lang][id]) || T.en[id] || id;
  const panels = [{ img: 'ship', id: 'p1' }, { img: 'fish', id: 'p2' }, { img: 'ship', id: 'p3' }, { img: 'harbour', id: 'p4' }, { img: 'notebook', id: 'p5' }, { img: 'island', id: 'p6' }];
  return { T, t, panels };
})();
